
default: &default
  adapter: postgresql
  encoding: unicode
  username: behzad
  password: p@ssw0rd
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: 194.5.195.63
  database: stories_development
  username: behzad
  password: p@ssw0rd

test:
  <<: *default
  database: stories_test

production:
  <<: *default
  database: stories_production
  username: stories
  password: <%= ENV['HOTELAPI_DATABASE_PASSWORD'] %>
